### ISSUE TITLE
Add GUI for options

### ISSUE THREAD

**Issue by Infocatcher** [Infocatcher/Console_Logger#3]
Special parts:
- [x] Options: implement export/import functionality (to/from clipboard) #4
- [x] Options: add search (filtration) #6
- [x] Options: prevent non-ASCII names #7
- [x] <del>Options: possible memory leaks for options.xul (and optionsOpener.xul) #8</del>
  (looks like Firefox bug, wontfix)
- [x] Options: add ability to disable all rules globally #9
- [x] Options: validate input data #10
- [x] Options: add ability to open *.log file #11
- [x] Options: implement export/import functionality (to/from file) #12
- [x] Options: force sort list of items by name #13
- [x] Options: add ability to open in tab #14
- [x] Options: indication of available and updated *.log files #15
- [x] Options: add ability to remove *.log file #16
- [x] Options: add localization #5
